Exclude non-jar files
mrsarm/jshell-plugin pull request #17
Opened 2023-01-19 01:12 UTC by davidnavas

In large enough projects and for ... reasons, you can sometimes wind up with non-jar files in your classpath. This makes jshell integration slightly easier as jshell is quite vocal about this and quits.

2023-01-19 22:24 UTC, mrsarm requested changes

2023-01-19 22:24 UTC, mrsarm commented on src/main/groovy/com/github/mrsarm/jshell/plugin/JShellPlugin.groovy
> +            pathSet = pathSet.findAll{ it.isDirectory() || it.toString().endsWith('.jar') }
Testing it locally with a sample project, I got this error:

```
$ gradle --console plain jshell
> Task :compileJava UP-TO-DATE
...
> No signature of method: java.lang.String.isDirectory() is applicable for argument types: () values: []
```

Looks like `it` is a `String` object and does not have a `isDirectory()` method.

2023-01-29 15:19 UTC, mrsarm commented on src/main/groovy/com/github/mrsarm/jshell/plugin/JShellPlugin.groovy
> +            pathSet = pathSet.findAll{ it.isDirectory() || it.toString().endsWith('.jar') }
```suggestion
            pathSet = pathSet.findAll{ new File(it.toString()).isDirectory() || it.toString().endsWith('.jar') }
```

Please apply this patch to your PR.

2023-01-29 15:20 UTC, merged

2023-01-29 17:30 UTC, davidnavas commented
Thank you.  For some reason I didn't get your first email.  I'm sorry to
have left this hanging.

My recollection is that I ran into the opposite problem, that "endsWith"
didn't work and I had to convert it into a String (this was before I added
the isDirectory() call).  I wonder if different gradle versions pass in
different types of objects :|  Well, your suggested change should address
this at least.  Thank you for committing it!


On Sun, Jan 29, 2023 at 7:20 AM Mariano Ruiz ***@***.***>
wrote:

> Merged #17 <https://github.com/mrsarm/jshell-plugin/pull/17> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mrsarm/jshell-plugin/pull/17#event-8382034002>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACJWT7HTV5IIEMWEK3S7EMTWU2DFJANCNFSM6AAAAAAT7X7R7U>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>